version: '1.1'
services:
  trino:
    hostname: trino
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino:ro
    networks:
      - trino-network

  mariadb:
    hostname: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083'
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
      - radosgw
    networks:
      - trino-network


  radosgw:
    hostname: radosgw
    image: 'quay.io/dparkes/zgw-dbstore:latest'
    ports:
      - '7480:7480'
    volumes:
      - /mnt:/var/lib/ceph/radosgw
    environment:
      ACCESS_KEY: hive
      SECRET_KEY: hive
      COMPONENT: zgw-dbstore
    networks:
      - trino-network


networks:
  trino-network:
    driver: bridge
